name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master, "ci/apk*" ]
  pull_request:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle 8.7 and generate wrapper
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: wrapper

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew || true

      - name: Configure Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Locate APK
        id: locate
        shell: bash
        run: |
          APK=$(find . -type f -path "*/build/outputs/apk/*/*debug*.apk" -print -quit)
          if [ -z "$APK" ]; then
            echo "No debug APK found" >&2
            exit 1
          fi
          echo "apk_path=$APK" >> "$GITHUB_OUTPUT"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: ${{ steps.locate.outputs.apk_path }}
          if-no-files-found: error
