name: flutter-android

on:
  push:
    branches: ["work"]
    paths: ["client_flutter/**"]
  pull_request:
    branches: ["main"]
    paths: ["client_flutter/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Prepare Flutter project
        working-directory: client_flutter
        run: |
          # Backup existing files
          mkdir -p ../backup
          cp -r lib ../backup/ 2>/dev/null || true
          cp pubspec.yaml ../backup/ 2>/dev/null || true
          
          # Remove existing Flutter project files to avoid conflicts
          rm -rf android ios linux macos web windows test .dart_tool .packages pubspec.lock
          
          # Create new Flutter project
          flutter create . --org com.manus.client --project-name manus_client
          
          # Restore custom files
          cp -r ../backup/lib . 2>/dev/null || true
          cp ../backup/pubspec.yaml . 2>/dev/null || true
          
      - name: Install dependencies
        working-directory: client_flutter
        run: flutter pub get
        
      - name: Build APK
        working-directory: client_flutter
        run: flutter build apk --debug --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL || 'http://10.0.2.2:8000' }}
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: client-apk
          path: client_flutter/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error

