name: Version bump on successful deploy

on:
  workflow_run:
    workflows: ["Deploy to Railway"]
    types: [completed]

jobs:
  bump:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bump version
        id: bump
        run: |
          python scripts/bump_version.py > new_version.txt
          echo "NEW_VERSION=$(cat new_version.txt)" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          NEW="${{ steps.bump.outputs.NEW_VERSION }}"
          git config user.name "autoversion-bot"
          git config user.email "autoversion-bot@users.noreply.github.com"
          git add VERSION manus2/app.py
          git commit -m "chore: bump version to ${NEW} [skip ci]" || echo "Nothing to commit"
          git push

      - name: Create tag
        run: |
          NEW="${{ steps.bump.outputs.NEW_VERSION }}"
          git tag -a "v${NEW}" -m "Release v${NEW}" || echo "Tag exists?"
          git push --tags || true
